apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
    worker_connections  4096;  ## Default: 1024
    }
    http {
    server {
    listen 80;
    root /usr/share/nginx/html/ ;
    index secret-aks;
    }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-index-file
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvsecret"
      containers:
      - name: nginx
        image: nginx:latest #Ajouter le docker du registre azure
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: nginx-index-file
            mountPath: "/usr/share/nginx/html/"
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    env: dev
    app: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-app
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: nginx-app
            port:
              number: 80
        pathType: Exact