apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-test
  region: eu-west-2

vpc:
  id: "vpc-0080b72d4ba4bbb02"
  subnets:
    private:
      eu-west-2a:
          id: "subnet-0fe5f8eb965d92d6c"
      eu-west-2b:
          id: "subnet-04af1f7c337d56332"
    public:
      eu-west-2a:
          id: "subnet-0141851db1da109e8"
      eu-west-2b:
          id: "subnet-06ba785aaf789b641"
nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.medium
    desiredCapacity: 2
    privateNetworking: true