on:
  workflow_dispatch:
    inputs:
      env:
        # Déclenchement Manuel du Pipeline
        description: 'Build Workflow Manually'
        required: true

name: Kubespray

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    # Use Ubuntu container to execute the action
    runs-on: ubuntu-latest
  
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Initializing git submodules
        working-directory: DEMO-AKS
        run: |
          git submodule init
          apt-get install azure-cli
          
      - name: Terraform Init AZURE
        working-directory: DEMO-AKS
        run: |
          terraform init 

      - name: Terraform Validate AZURE
        working-directory: DEMO-AKS
        run: |
          terraform validate

      - name: Terraform Apply AZURE
        working-directory: DEMO-AKS
        run: |
          terraform apply -auto-approve